[package]
name = "ats2-cli"
description = "The ats2llvm binary: a thin controller wiring the application use cases to infrastructure."
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "ats2llvm"
path = "src/main.rs"

[[bin]]
name = "ats2repl"
path = "src/repl.rs"

[dependencies]
ats2-infrastructure = { path = "../infrastructure" }
ats2-application = { path = "../application" }
ats2-domain = { path = "../domain" }